### ISSUE TITLE
Question about substitute() method

### ISSUE THREAD

**Issue by kgreenek** [andrew-gresyk/HFSM#4]
When is the `substitute()` method called on a State implementation?

From reading through the tests, it looks like it's called on a state before
`enter()` on the new state, and before `leave()` is called on the previous state.

Is that always the case? Just want to make sure I understand that correctly.

When would one typically want to implement that method?

Thanks!

**Comment by andrew-gresyk** [comment]
`substitute()` gives an option for the state to divert the incoming transition to another state.

It helps maintaining sub-machine (or 'region') encapsulation in a hierarchy.

Normally, the way I approach coming up with a structure for a particular state machine by breaking down a story into a set of atomic features.
This way, every feature becomes either a **state** (if it doesn't change over time), or a **sub-machine** (if it does).

Consider the example from video games. Suppose we have a weapon cycle that looks like this:
on trigger: (firing) -> (recoiling) -> (firing) -> (recoiling) -> (reloading) -> (firing)

With the above approach that would be a sub-machine within a larger stare machine of a player character, who is going to trigger it.

Now there's a potential problem with that sub-machine: if the weapon has no ammo, it shouldn't go into (firing) state, it should go into (reloading) instead!

The ammo check can be done by the player character, but that would create a dependency.

In the interest of 'good design' you want weapon sub-machine to be loosely coupled, and the player character not needing to know about the inner workings of a weapon.
Player character should initiate the transition to the weapon sub-machine directly, rather than into the (firing) sub-state of a weapon.

This is where `substitute()` comes in.

If we add ammo check to `substitute()` in the (firing) state - we can hide the implementation of the weapon and make the state machine simpler, by removing inter-dependencies between different regions of the player character state machine.

**Comment by andrew-gresyk** [comment]
Another example of the same idea is the jumping cycle of a character in a platformer game (like mario).

Consider the following cycle in the jumping sub-machine (remember the first state is implicitly activated by default if we transition into the sub-machine region):
(falling) -> (on ground) -> (jumping)

Because the first state is (falling) with the `substitute()` that would go directly into (on ground) if we collide with the ground surface, we can always safely transition into the region, and we can afford to be completely oblivious about the collision with the ground.

Which can happen, if we, for example spawn into the game, for the first time in some hardcoded location that may or may not be above the ground.

**Comment by andrew-gresyk** [comment]
I gave a [talk](https://www.meetup.com/CppLondon/events/237580202/) at the [C++ London](https://www.meetup.com/CppLondon) meetup last year.

The videos a cringeworthy, but might clear up some details for you, if you can suffer through me being terrible at presenting :)
[part 1](https://skillsmatter.com/skillscasts/9901-hierarchical-fsm)
[part 2](https://skillsmatter.com/skillscasts/10157-hierarchical-fsm-part-2)

They also explain the other two transition types (`resume()` and `schedule()`), composite and orthogonal regions, and such.

**Comment by andrew-gresyk** [comment]
In reality, so long as your state machine is relatively simple, you probably wouldn't care too much about architectural considerations.

But when the complexity of the FSM grows high enough, it becomes tedious to maintain it.
That's when stuff like `substitute()` and the upcoming `linger()` (which is what I'm working on right now, called before `leave()` and allowing a state to delay the original transition) are very helpful in reducing interdependencies between states and regions thus reducing overall complexity and maintenance costs.

**Comment by kgreenek** [comment]
Got it! That makes a ton of sense. Thanks for the detail!

I'll check out your videos too. Good stuff :)
