### ISSUE TITLE
Add ability to save current state as .dot file (or similar)

### ISSUE THREAD

**Issue by kgreenek** [andrew-gresyk/HFSM#6]
This would be very helpful for debugging run-time issues.

**Comment by andrew-gresyk** [comment]
I've implemented something related to this in my experimental branch at home: an [automatic structure visualizer](https://imgur.com/pCq2rMu).

The interface looks like this:
```
struct PrefixName {
	const wchar_t* prefix;
	const char* name;
};
using MachineStructure = ArraySlice<PrefixName>;
const MachineStructure& structure() const;

using MachineActivity  = ArraySlice<char>;
const MachineActivity& activity();
```

`activity()` gives you an array of update count since a state has been activated (if positive) or deactivated (if negative), clamped in [-128, 127].

Would this work for your needs?
